apiVersion: v1
kind: Service
metadata:
  name: my-nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: preview-my-nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  strategy:
    blueGreen:
      activeService: my-nginx-svc
      previewService: preview-my-nginx-svc
      autoPromotionEnabled: true
      autoPromotionSeconds: 180
      
      
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 80
